import { expect, test } from "bun:test";

import type { StarlightRouteData } from "@astrojs/starlight/route-data";

import { autoCollapseLongSidebarGroups, humanizeAutogeneratedGroupLabels } from "../src/plugins/kokosa-blog/libs/sidebar";

type Sidebar = StarlightRouteData["sidebar"];
type Entry = Sidebar[number];

function autoGroup(label: string, entries: Sidebar = [], directory = label): Entry {
  return { autogenerate: { directory }, badge: undefined, collapsed: false, entries, label, type: "group" };
}

function manualGroup(label: string, entries: Sidebar = []): Entry {
  return { badge: undefined, collapsed: false, entries, label, type: "group" };
}

function autoLink(label: string): Entry {
  return { attrs: {}, autogenerate: { directory: "create" }, badge: undefined, href: "/create", isCurrent: false, label, type: "link" };
}

test("replaces hyphens with spaces in autogenerated group labels", () => {
  // Given
  const sidebar: Sidebar = [
    manualGroup("Study", [autoGroup("oc-profile", [autoGroup("nested-dir"), autoLink("01-kokosa")])]),
    autoGroup("create"),
  ];

  // When
  humanizeAutogeneratedGroupLabels(sidebar);

  // Then
  const study = sidebar[0];
  expect(study).toEqual(
    manualGroup("Study", [autoGroup("oc profile", [autoGroup("nested dir", [], "nested-dir"), autoLink("01-kokosa")], "oc-profile")]),
  );
  expect(sidebar[1]).toEqual(autoGroup("create"));
});

test("leaves manual group labels and link labels untouched", () => {
  // Given
  const sidebar: Sidebar = [manualGroup("Recent-posts"), autoLink("my-oc"), autoGroup("create", [autoLink("01-kokosa")])];

  // When
  humanizeAutogeneratedGroupLabels(sidebar);

  // Then
  expect(sidebar[0]).toEqual(manualGroup("Recent-posts"));
  expect(sidebar[1]).toEqual(autoLink("my-oc"));
  expect(sidebar[2]).toEqual(autoGroup("create", [autoLink("01-kokosa")]));
});

function longLinks(count: number): Sidebar {
  return Array.from({ length: count }, (_, i) => autoLink(`entry-${i + 1}`));
}

test("collapses groups with more than 5 entries by default", () => {
  // Given
  const sidebar: Sidebar = [manualGroup("Study", [autoGroup("practice", longLinks(6))])];

  // When
  autoCollapseLongSidebarGroups(sidebar);

  // Then
  expect(sidebar[0].type).toBe("group");
  if (sidebar[0].type !== "group") throw new Error("unreachable");
  expect(sidebar[0].entries[0].type).toBe("group");
  if (sidebar[0].entries[0].type !== "group") throw new Error("unreachable");
  expect(sidebar[0].entries[0].collapsed).toBe(true);
});

test("keeps groups with 5 or fewer entries expanded", () => {
  // Given
  const sidebar: Sidebar = [manualGroup("Study", [autoGroup("notes", longLinks(5))])];

  // When
  autoCollapseLongSidebarGroups(sidebar);

  // Then
  expect(sidebar[0].type).toBe("group");
  if (sidebar[0].type !== "group") throw new Error("unreachable");
  expect(sidebar[0].entries[0].type).toBe("group");
  if (sidebar[0].entries[0].type !== "group") throw new Error("unreachable");
  expect(sidebar[0].entries[0].collapsed).toBe(false);
});

test("collapses long nested groups recursively while leaving short siblings alone", () => {
  // Given
  const sidebar: Sidebar = [
    manualGroup("Study", [autoGroup("notes", longLinks(2)), autoGroup("practice", longLinks(7))]),
    manualGroup("Create", [autoGroup("oc-profile", [autoLink("01-kokosa")])]),
  ];

  // When
  autoCollapseLongSidebarGroups(sidebar);

  // Then
  const study = sidebar[0];
  expect(study.type).toBe("group");
  if (study.type !== "group") throw new Error("unreachable");
  const notes = study.entries[0];
  const practice = study.entries[1];
  expect(notes.type).toBe("group");
  expect(practice.type).toBe("group");
  if (notes.type !== "group" || practice.type !== "group") throw new Error("unreachable");
  expect(notes.collapsed).toBe(false);
  expect(practice.collapsed).toBe(true);

  const create = sidebar[1];
  expect(create.type).toBe("group");
  if (create.type !== "group") throw new Error("unreachable");
  expect(create.entries[0].type).toBe("group");
  if (create.entries[0].type !== "group") throw new Error("unreachable");
  expect(create.entries[0].collapsed).toBe(false);
});
