import type { StarlightRouteData } from "@astrojs/starlight/route-data";

/**
 * Sidebar groups with more entries than this threshold start collapsed.
 */
const SIDEBAR_COLLAPSE_THRESHOLD = 5;

/**
 * Autogenerated sidebar groups derive their labels from directory names.
 * Treat "-" as a space so kebab-case directories ("oc-profile") render as
 * space-separated words ("oc profile"). Manual groups and link labels
 * (page titles) are left untouched.
 */
export function humanizeAutogeneratedGroupLabels(sidebar: StarlightRouteData["sidebar"]): void {
  for (const entry of sidebar) {
    if (entry.type === "group") {
      if ("autogenerate" in entry) {
        entry.label = entry.label.replaceAll("-", " ");
      }
      humanizeAutogeneratedGroupLabels(entry.entries);
    }
  }
}

/**
 * Collapse sidebar groups with more than {@link SIDEBAR_COLLAPSE_THRESHOLD}
 * entries by default. Starlight keeps a group open when the current page is
 * inside it, so navigation to the group's own pages is unaffected.
 */
export function autoCollapseLongSidebarGroups(sidebar: StarlightRouteData["sidebar"]): void {
  for (const entry of sidebar) {
    if (entry.type === "group") {
      if (entry.entries.length > SIDEBAR_COLLAPSE_THRESHOLD) {
        entry.collapsed = true;
      }
      autoCollapseLongSidebarGroups(entry.entries);
    }
  }
}
